### ISSUE TITLE
Http redirection

### ISSUE THREAD

**Issue by jdessaint** [l3-team/CasBundle#11]
Hello,
I noticed that the redirection to the CAS server is only for HTTPS page. Is there a possibility to redirect to simple HTTP page ?
Here is my configuration :
```
l3_cas:
    host: xx.xx.xx.xx
    path: cas
    port: 443
    ca: false
    handleLogoutRequest: true
    casLogoutTarget: localhost:4200
    force: true
```
Thank you
