### ISSUE TITLE
Utilisation avec FOSUserBundle

### ISSUE THREAD

**Issue by asebert** [l3-team/CasBundle#2]
Bonjour et merci pour cette intégration du CAS

J’utilise FosUserBundle, je n'ai pas de problème avec la configuration **force: true** mais lorsque que je passe se paramètre a false.

J'ai cette belle erreur **Username "__NO_USER__" does not exist** ... ce qui est normal 

Avez-vous plus de précision sur l'usage du paramètre force: false ??

**Comment by mhetru** [comment]
Bonjour, l'utilisation de FOSUserBundle a été testé que par un seul établissement universitaire (Université Lille1) pour l'application carte de voeux. Ils m'ont signalé qu'ils avaient remarqué qu'il était possible de détourner la règle de gestion du CASBundle simplement en insérant une entrée dans la table utilisateurs de FOSUserBundle avec l'identifiant ```__NO_USER__``` car ce dernier est retourné lorsqu'il n'y a pas d'appel au serveur CAS. L'identifiant ```__NO_USER__``` est en quelque sorte un utilisateur particulier pour la partie anonyme (lorsque force: false est positionné dans le parameters.yml).

Cordialement.

**Comment by asebert** [comment]
C'est bien ça ! j'ai utilisé la fonction chain_provider de Symfony

//security.yml
```yml
    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    __NO_USER__:
                        password:
                        roles: ROLE_ANO
        fos_userbundle:
            id: fos_user.user_provider.username
```

Merci.
