### ISSUE TITLE
Two authentications strategies

### ISSUE THREAD

**Issue by vittore** [l3-team/CasBundle#26]
Hi,

what I want to do is two authentications strategies:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/289512/154532489-f5bbb4de-23ab-4da9-af7f-068936a85a0d.png">

- centralized use CAS
- local use standard symfony users

What I have done:

- a template security/login.html.twig with two link, one for cas, one for local authentication
- a classical login form for local login
- a redirect to cas server for login and logout

This is the controller:
```
class SecurityCasController extends AbstractController
{
    /**
     * @Route("/login", name="login", methods={"GET", "POST"})
     */
    public function login(AuthenticationUtils $authenticationUtils)
    {
        return $this->render(
            'security/login.html.twig',
            [
            ]
        );
    }


    /**
     * @Route("/cas/login", name="cas-login", methods={"GET", "POST"})
     */
    public function caslogin(Request $request)
    {
        if (!isset($_SESSION)) {
            session_start();
        }

        session_destroy();
        $url = 'https://'.$this->getParameter('cas_host') . $this->getParameter('cas_path') . '/login?service=';
        return $this->redirect($url . urlencode($request->getSchemeAndHttpHost()));
    }

    /**
     * @Route("/cas/logout", name="cas-logout", methods={"GET", "POST"})
     */
    public function casLogout(Request $request)
    {
        if (!isset($_SESSION)) {
            session_start();
        }

        session_destroy();
        $url = 'https://'.$this->getParameter('cas_host') . $this->getParameter('cas_path') . '/logout?service=';
        return $this->redirect($url . urlencode($request->getSchemeAndHttpHost()));
    }
```

This is security.yaml:
```
security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  providers:
    app_users:
      entity: { class: App\Entity\User, property: email }

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    login_choice:
      pattern: ^/login
      security: false
    local_login:
      pattern: ^/local/login
      security: false
    cas_login:
      pattern: ^/cas/login
      security: false
    main:
      anonymous: ~
      pattern: ^/
      security: true
      cas: true
      provider: app_users
      form_login:
        provider: app_users
        login_path: login
        check_path: login
  access_control:
    - { path: ^/, role: ROLE_USER }
```

My question: is this approach correct?

Thanks in advance for your ideas.
v.
